name: "Sync approved PRs to internal codebase"
description: "Sync approved Github PRs to the Espressif's internal IDF integration"
branding:
  icon: "fast-forward"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
