name: "GitHub to JIRA Issue Sync [Deprecated]"
description: "DEPRECATED: Performs simple one-way syncing of GitHub issues into JIRA. Please migrate to the new action at https://github.com/espressif/sync-jira-actions."
branding:
  icon: "fast-forward"
  color: "green"
inputs:
  cron_job:
    description: >
      Whether the action is run as a cron job.
      Set true to trigger syncing of new PRs.
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
